--- Metrics options tree

-- Import smart constructors
options_builder.import_into(this)

-- Shader scopes
PAGE = page {
	{ id = "metrics" },
	track {
		id = "lua_gcstep",
		def = 400,
		min = 1,
		max = 1000,
		step = 10,
	},
	track {
		id = "mouse_buffer_size",
		def = 1024,
		min = 64,
		max = 2048,
		step = 32,
	},
	track {
		id = "keyboard_buffer_size",
		def = 128,
		min = 64,
		max = 512,
		step = 32,
	},
}