--- First person death options tree

-- Import smart constructors
options_builder.import_into(this)

-- Shader scopes
PAGE = page {
	{ id = "first_person_death" },
	list_bool { id = "first_person_death" },
	track {
		id = "first_person_death_position_smoothing",
		def = 6,
		min = 1,
		max = 30,
		step = 1,
	},
	track {
		id = "first_person_death_direction_smoothing",
		def = 12,
		min = 1,
		max = 30,
		step = 1,
	},
}