--- Optimizations options tree

-- Import smart constructors
options_builder.import_into(this)

-- Shader scopes
PAGE = page {
	{ id = "optimizations" },
	list_bool { id = "spawn_antifreeze" },
	track {
		id = "spawn_antifreeze_batch",
		def = 2,
		step = 1,
		max = 50,
	},
	track {
		id = "lua_gcstep",
		def = 400,
		step = 10,
	},
	track {
		id = "mouse_buffer_size",
		def = 1024,
		step = 32,
	},
	track {
		id = "keyboard_buffer_size",
		def = 128,
		step = 32,
	},
}